### ISSUE TITLE
Weird errors

### ISSUE THREAD

**Issue by QsoftStudios** [nomorecoin/tAPIbot#4]
All the dependences are installed. When run the program crashes giving this error.

Greetings, human. tAPI-bot loading...
Traceback (most recent call last):
  File "Application.py", line 11, in <module>
    trader = trader.trade()
  File "/home/user/tAPIbot/tapi/trader.py", line 19, in **init**
    self.keyCheck()
  File "/home/user/tAPIbot/tapi/trader.py", line 80, in keyCheck
    self.rights = test.poll().get('return').get('rights')
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by energetixuser** [comment]
Have a same problem

**Comment by Hormold** [comment]
Have a same problem! =(

**Comment by elzorrorebelde** [comment]
from [bitcointalk thread on tAPI-bot](https://bitcointalk.org/index.php?topic=197526.msg2056151#msg2056151): KeyError printing existing orders, investigating. Set verbose = False to bypass this issue.

**Comment by BeardyWalrus** [comment]
I fixed the existing order bug in my latest pull request.

**Comment by nomorecoin** [comment]
Closing as fixed, as BeardyWalrus pull request is merged.
